### ISSUE TITLE
no mqs bin file installed

### ISSUE THREAD

**Issue by phaibin** [MgaMPKAy/aliyun-mqs#2]
After installed, can't find mqs command from cli.

**Comment by phaibin** [comment]
UPDATE:
Can't find mqs command by gem install directly. But can find from git repo. So must use bundle exec mqs.

**Comment by MgaMPKAy** [comment]
This repo and rubygems.org are out of sync for some days. I have released a new version (v0.1.1) to rubygems.org

**Comment by phaibin** [comment]
Thanks!
